// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubceqmklnqmqurutymol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViY2VxbWtsbnFtcXVydXR5bW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTQ4MDcsImV4cCI6MjA1OTA5MDgwN30.ndbjE2sGBQdK3S-qVWAeurS6SW4f7oXrLUzZ_KdlW34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);